spring:
  application:
    name: BaoAnMedicine
  datasource:
    url: "jdbc:mysql://localhost:3306/BaoAn_db?createDatabaseIfNotExist=true"
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

app:
  # PHẢI DÀI và BÍ MẬT: Chuỗi này dùng để ký (sign) JWT Token.
  # Chiều dài khuyến nghị là 256 bit (khoảng 32 ký tự).
  jwt-secret: YOUR_ULTRA_SECRET_KEY_FOR_JWT_SIGNATURE_NEED_TO_BE_LONG_AND_RANDOM
  # Thời gian hết hạn tính bằng miligiây (86400000 ms = 24 giờ)
  jwt-expiration-milliseconds: 86400000


